spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/site/count-for-page/count-page.db
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
