spring:
  freemarker:
    # 选用static的原因是spring默认页面加载也是static
    template-loader-path: classpath:/static
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
